openapi: 3.1.0
info: 
  title: Strava GPT Backend
  version: 1.0.0
servers:
  - url: https://stravagptfaby.vercel.app
paths:
  /api/oauth/openai-authorize:
    get:
      tags:
        - oauth
      operationId: openaiAuthorize
      summary: Prépare le state et redirige vers Strava avec redirect_uri=ChatGPT
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: string
        - in: query
          name: redirect_uri
          required: true
          schema:
            type: string
            format: uri
          description: URL de callback ChatGPT (variable du Builder)
      responses:
        "302":
          description: Redirection vers Strava
      x-openai-isConsequential: false
  /api/oauth/token-openai:
    post:
      tags:
        - oauth
      operationId: openaiToken
      summary: Échange le code contre des tokens Strava (via backend proxy)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - code
                - redirect_uri
              properties:
                code:
                  type: string
                redirect_uri:
                  type: string
                  format: uri
      responses:
        "200":
          description: OK, tokens sauvegardés côté serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                    example: true
                  athlete_id:
                    type: integer
                    example: 12345678
                  expires_at:
                    type: integer
                    example: 1758000000
        "502":
          description: Provider error
      x-openai-isConsequential: true
  /api/link:
    post:
      tags:
        - oauth
      operationId: linkUserAthlete
      summary: Lie un user_id GPT à l’athlete_id Strava
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - athlete_id
              properties:
                user_id:
                  type: string
                athlete_id:
                  type: integer
      responses:
        "200":
          description: Mapping créé
      x-openai-isConsequential: true
