openapi: 3.1.1
info:
  title: Connexion Strava - GPT Actions API
  version: "1.0.0"
  description: >
    Backend pour le GPT "Connexion Strava".
    - POST /api/token : échange un code court-vivant (OTC) contre un JWT d'application.
    - GET  /api/activities : liste des activités des 28 derniers jours (protégé par Bearer).
    - GET  /api/activities/{id} : détail d’une activité (protégé par Bearer).
    - GET  /api/me : profil athlète (protégé par Bearer).

servers:
  - url: https://stravagpt.vercel.app

paths:
  /api/token:
    post:
      summary: Exchange one-time code (OTC) for an application JWT
      operationId: exchangeToken
      description: >
        Reçoit le code court-vivant (OTC) délivré après OAuth et renvoie un JWT d'application.
        Utiliser ensuite `Authorization: Bearer {token}` pour les endpoints protégés.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              required: [code]
              properties:
                code:
                  type: string
                  description: One-time code received from the OAuth callback via the builder
                  example: "OtC_9J3nZk..."
      responses:
        '200':
          description: App token issued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: Invalid or expired code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalid_grant:
                  value:
                    error: invalid_grant
                    error_description: Code invalid or expired
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/activities:
    get:
      summary: List last 28 days of activities
      operationId: getActivities
      security:
        - BearerAuth: []
      description: >
        Retourne la liste des activités des 28 derniers jours.
        Requiert l'en-tête Authorization: Bearer {token}.
      responses:
        '200':
          description: Activities list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesResponse'
        '401':
          description: Missing or invalid bearer token (re-run OAuth then call /api/token)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorized:
                  value:
                    error: unauthorized
                    error_description: Bearer token missing or invalid
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/activities/{id}:
    get:
      summary: Get detailed activity by id
      operationId: getActivityDetail
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Strava activity id
          schema:
            type: integer
      responses:
        '200':
          description: Detailed activity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityDetail'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                invalid_request:
                  value:
                    error: invalid_request
                    error_description: Invalid activity id
        '401':
          description: Missing or invalid bearer token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Activity not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/me:
    get:
      summary: Get athlete profile
      operationId: getProfile
      security:
        - BearerAuth: []
      description: >
        Renvoie les informations principales du profil athlète.
        Requiert l'en-tête Authorization: Bearer {token}.
      responses:
        '200':
          description: Athlete profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        '401':
          description: Missing or invalid bearer token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                unauthorized:
                  value:
                    error: unauthorized
                    error_description: Bearer token missing or invalid
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponse:
      type: object
      additionalProperties: false
      properties:
        error:
          type: string
          example: unauthorized
        error_description:
          type: string
          example: Bearer token missing or invalid

    TokenResponse:
      type: object
      additionalProperties: false
      properties:
        token:
          type: string
          description: Application JWT to use as Bearer token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        token_type:
          type: string
          example: bearer
        expires_in:
          type: integer
          example: 604800

    Activity:
      type: object
      description: Activité normalisée pour l’analyse 28 jours
      additionalProperties: false
      properties:
        id:
          type: integer
          example: 16711309904
        name:
          type: string
          example: "Course à pied le matin"
        date:
          type: string
          description: Horodatage lisible (peut ne pas être ISO 8601)
          example: "2025-08-31 10:08"
        suffer_score:
          type: number
          example: 22
        distance_meter:
          type: number
          example: 13618.6
        time_moving:
          type: integer
          example: 4835
        time_elapsed:
          type: integer
          example: 4971
        avg_hr:
          type:
            - number
            - "null"
          example: 124.6
        avg_watts:
          type:
            - number
            - "null"
          example: null
        elevation:
          type: number
          description: Dénivelé positif cumulé (m)
          example: 55
        year:
          type: integer
          example: 2025
        month:
          type: integer
          example: 8
        week:
          type: integer
          description: Semaine ISO (ou logique interne)
          example: 35
        type:
          type: string
          example: "Run"
        commute:
          type: boolean
          example: false
        comute:
          type: boolean
          deprecated: true
          description: Alias historique (préférer 'commute')
          example: false
        avg_cadence:
          type:
            - number
            - "null"
          example: 88.4
        year_week:
          type: string
          example: "2025-35"

    ActivitiesResponse:
      type: object
      additionalProperties: false
      properties:
        total:
          type: integer
          example: 12
        items:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
      example:
        total: 2
        items:
          - id: 16711309904
            name: "Course à pied le matin"
            date: "2025-08-31 10:08"
            suffer_score: 22
            distance_meter: 13618.6
            time_moving: 4835
            time_elapsed: 4971
            avg_hr: 124.6
            avg_watts: null
            elevation: 55
            year: 2025
            month: 8
            week: 35
            type: "Run"
            commute: false
            avg_cadence: 88.4
            intensity: 16.38055843
            charge: 223.080273
            year_week: "2025-35"
          - id: 16711309905
            name: "Sortie vélo endurance"
            date: "2025-09-01 07:42"
            suffer_score: 45
            distance_meter: 42153.2
            time_moving: 4763
            time_elapsed: 4820
            avg_hr: 131.2
            avg_watts: 185.4
            elevation: 420
            year: 2025
            month: 9
            week: 36
            type: "Ride"
            commute: false
            avg_cadence: 88
            year_week: "2025-36"

    Profile:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          example: 12345678
        username:
          type: string
          example: "benjamin"
        firstname:
          type: string
          example: "Benjamin"
        lastname:
          type: string
          example: "Dupont"
        sex:
          type: string
          example: "M"
        city:
          type: string
          example: "Paris"
        country:
          type: string
          example: "France"
        profile_medium:
          type: string
          example: "https://example.com/athlete/med.jpg"
        profile:
          type: string
          example: "https://example.com/athlete/full.jpg"
        premium:
          type: boolean
          example: false

    ActivityDetail:
      description: Détail d’activité — étend Activity avec des champs additionnels
      allOf:
        - $ref: '#/components/schemas/Activity'
        - type: object
          additionalProperties: false
          properties:
            description:
              type:
                - string
                - "null"
              example: "Séance tempo sur berges"
            device_name:
              type:
                - string
                - "null"
              example: "Garmin Forerunner 955"
            calories:
              type:
                - number
                - "null"
              example: 820
            average_speed:
              type:
                - number
                - "null"
              description: m/s
              example: 3.75
            pace_sec_per_km:
              type:
                - integer
                - "null"
              description: Allure en secondes par km (si applicable)
              example: 267
            max_hr:
              type:
                - number
                - "null"
              example: 178
            max_watts:
              type:
                - number
                - "null"
              example: 540
            elapsed_seconds:
              type:
                - integer
                - "null"
              description: Alias lisible de time_elapsed
              example: 4971
            gear_id:
              type:
                - string
                - "null"
              example: "g1234567"
            splits_metric:
              type:
                - array
                - "null"
              description: Splits métriques si disponibles
              items:
                type: object
            splits_standard:
              type:
                - array
                - "null"
              description: Splits impériaux si disponibles
              items:
                type: object
            laps:
              type:
                - array
                - "null"
              items:
                type: object
            best_efforts:
              type:
                - array
                - "null"
              items:
                type: object
